angular.module('app')
.controller('vxSampleController', ["$scope", "$timeout", function ($scope, $timeout) {
    $scope.vxSampleData = [];
    $scope.showGrid = false;
    var original = [
            {
                readOnly: "Y",
                transferFromCustomer: "Alpine Ski House A Alpine Ski House AAlpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174",
                status: "Pending",
                dt: "SEP 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-1",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: true
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House B",
                transferFromAssignment: "NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-174 NB-FY15-XYZ-Coho-1746",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-2",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House C",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-3",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House c",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-5",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House c",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1746",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-6",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House B",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1746",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-7",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House d",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-8",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House f",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-9",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House f",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-10",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House f",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-11",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House j",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-12",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House j",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-13",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House j",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-14",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House j",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-15",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House k",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-16",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House k",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-17",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House k",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-18",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House k",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-19",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House l",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-20",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House B",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-21",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-22",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-23",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-24",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-25",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-26",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House B",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 22, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-27",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "02:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-28",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "Y",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-29",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: true
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-30",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 22nd,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-31",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-32",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House B",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC + 5:30) India Time (New Delhi)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-33",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Onsite",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-34",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "N",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745 NB-FY15-XYZ-Coho-1745 NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-35",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: false
            },
            {
                readOnly: "Y",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet",
                laborId: "xxx-xxx-xxxx-36",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: true
            },
            {
                readOnly: "Y",
                transferFromCustomer: "Alpine Ski House A",
                transferFromAssignment: "NB-FY15-XYZ-Coho-1745",
                status: "Pending",
                dt: "APR 21, 2014",
                labor: "01:45",
                date: "APR 21st,2014",
                category: "Previsit",
                timezone: "(UTC - 5:00)Pacific Time(US&Canada)",
                notes: "Lorem ipsum dolor sit amet b",
                laborId: "xxx-xxx-xxxx-37",
                errors: {},
                errorsShow: false,
                disabled: false,
                transferStatus: 0,
                locked: true
            }
    ];

    _.each(original, function (record, k) {
        _.each(_.range(100), function (i, j) {
            var rec = angular.copy(record);
            rec.index = k + '_' + j;
            rec.laborId = 'XXX-XXXX-XXXX' + '_' + rec.index;
            rec.category = _.sample(['previsit', 'onsite', 'general']);
            rec.customer = record.transferFromCustomer,
            rec.engagement = _.sample(['Coho Vineyard', 'Fist Up Consultants']),
            rec.assignment = record.transferFromAssignment,
            rec.userAlias = _.sample(['asparida', 'prasadne', 'ruprawat']),
            $scope.vxSampleData.push(rec);
        });
    });

    $scope.vxSampleConfig = {
        enableDropdownsInHeader: true,
        ddSort: true,
        ddGroup: false,
        defaultGrouping: { enabled: false, column: 2, columnName: 'customer' },
        groupedSelectionEnabled: true,
        columnFilteringEnabled: true,
        groupedColumnHidingEnabled: false,
        selectionEnabled: true,
        multiSelectionEnabled: true,
        multiSelectionDependentCol: null,
        onSelectionReturnCol: 'laborId',
        showGridStats: true,
        showGridOptions: true,
        data: $scope.vxSampleData,
        vxFilteredData: [],
        showTable: false,
        columnDefConfigs: [
            { id: 'dt', columnName: 'Date', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, width: '120' },
            { id: 'customer', columnName: 'Customer', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, dropDownEnabled: true },
            { id: 'engagement', columnName: 'Engagement', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, dropDownEnabled: true, hidden: true, locked: false },
            { id: 'assignment', columnName: 'Assignment', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, dropDownEnabled: true },
            { id: 'userAlias', columnName: 'User', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, dropDownEnabled: true },
            { id: 'labor', columnName: 'Labor', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: false },
            { id: 'timezone', columnName: 'Timezone', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: false, hidden: true },
            { id: 'status', columnName: 'Status', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: false },
            { id: 'category', columnName: 'Category', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: true, dropDownEnabled: true },
            { id: 'laborId', columnName: 'Labor ID', renderDefn: false, ddSort: true, ddGroup: false, ddFilters: false, primary: true }
        ]
    };
    console.log('length : ' + $scope.vxSampleData.length);

    $scope.$on('vsRepeatInnerCollectionUpdated', function () {
        console.log('vsRepeatInnerCollectionUpdated');
    });

    $scope.$on('vsRepeatScrolled', function () {
        console.log('vsRepeatScrolled');
    });

    $scope.$on('vxGridRowSelectionChange', function (e, data) {
        console.log('vxGridRowSelectionChange');
        console.log(e);
        console.log(data);
    });

    $scope.$on('vxGridRowMultiSelectionChange', function (e, data) {
        console.log('vxGridRowMultiSelectionChange');
        console.log(e);
        console.log(data);
    });

}]);